@startuml
'https://plantuml.com/class-diagram
ex46 --|> WordFrequency
ex46 <|-- WordFrequency

"exercise46_input.txt" --|> ex46

"output.txt" <|-- ex46

class WordFrequency {
loopWordInput()
}
@enduml